# Generated by Django 3.1.7 on 2021-03-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('date_listed', models.DateField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=25)),
                ('required_experience', models.CharField(max_length=25)),
                ('salary', models.CharField(max_length=7)),
                ('title', models.CharField(max_length=100)),
                ('url', models.TextField()),
                ('created_at', models.DateField()),
            ],
        ),
    ]
