# Generated by Django 3.1.7 on 2021-03-30 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendFramework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FrontendFramework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend_framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.backendframework')),
                ('frontend_framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.frontendframework')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='tech_stack',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='listings.techstack'),
            preserve_default=False,
        ),
    ]
