# Generated by Django 3.1.7 on 2021-03-31 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20210331_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='tech_stack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.techstack'),
        ),
    ]
