# Generated by Django 3.1.7 on 2021-03-31 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20210331_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='salary',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
