# Generated by Django 3.1.7 on 2021-03-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20210331_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
